### ISSUE TITLE
Why it lags?

### ISSUE THREAD

**Issue by Light-Lens** [aditineemkar/My-origami-website#1]
HI!, I'm a 13 year old dev too, as JavaScript being one of my first languages it's pretty impressive that you have made this without using JavaScript but just for better of this site, don't you think that this lags? I mean seriously is it just me or it actually lags?

Also releasing it on Github is pretty confusing to me as you can use something like GoDaddy or Hostinger to get it up and running really quickly and easily, but yeah it's ur choice.

I guess you should use something like Flask or JavaScript to make it smoother and better.

**Comment by aditineemkar** [comment]
HI!, As I am a beginner in programming, I have learnt only HTML, CSS and a bit of JavaScript, so it was complex for me to create a website using JavaScript, and I had some timelines to submit this project so I needed to code in a platform suitable for me, so I choose GitHub and HTML, Thanks for raising this issue. I will try my best to make it using some other platform.

**Comment by aditineemkar** [comment]
> HI!, I'm a 13 year old dev too, as JavaScript being one of my first languages it's pretty impressive that you have made this without using JavaScript but just for better of this site, don't you think that this lags? I mean seriously is it just me or it actually lags?
> 
> Also releasing it on Github is pretty confusing to me as you can use something like GoDaddy or Hostinger to get it up and running really quickly and easily, but yeah it's ur choice.
> 
> I guess you should use something like Flask or JavaScript to make it smoother and better.

HI!, As I am a beginner in programming, I have learnt only HTML, CSS and a bit of JavaScript, so it was complex for me to create a website using JavaScript, and I had some timelines to submit this project so I needed to code in a platform suitable for me, so I choose GitHub and HTML, Thanks for raising this issue. I will try my best to make it using JavaScript or on some other platform.

**Comment by arathimahesh** [comment]
Hi, Yes it's lagging.

**Comment by Light-Lens** [comment]
> > HI!, I'm a 13 year old dev too, as JavaScript being one of my first languages it's pretty impressive that you have made this without using JavaScript but just for better of this site, don't you think that this lags? I mean seriously is it just me or it actually lags?
> > Also releasing it on Github is pretty confusing to me as you can use something like GoDaddy or Hostinger to get it up and running really quickly and easily, but yeah it's ur choice.
> > I guess you should use something like Flask or JavaScript to make it smoother and better.
> 
> HI!, As I am a beginner in programming, I have learnt only HTML, CSS and a bit of JavaScript, so it was complex for me to create a website using JavaScript, and I had some timelines to submit this project so I needed to code in a platform suitable for me, so I choose GitHub and HTML, Thanks for raising this issue. I will try my best to make it using some other platform.

No, problem. It's totally fine using Github, but using Hostinger will make it run smoother. And just for the animations you can use Javascript which is not that hard. JS is one of the most easiest langs and even i thought at my early days that it's hard but it's not. Just a small lang change in your code will make your website much faster, smoother and easier to add more animations in future. BTW it's great, GOOD JOB!

**Comment by aditineemkar** [comment]
> > > HI!, I'm a 13 year old dev too, as JavaScript being one of my first languages it's pretty impressive that you have made this without using JavaScript but just for better of this site, don't you think that this lags? I mean seriously is it just me or it actually lags?
> > > Also releasing it on Github is pretty confusing to me as you can use something like GoDaddy or Hostinger to get it up and running really quickly and easily, but yeah it's ur choice.
> > > I guess you should use something like Flask or JavaScript to make it smoother and better.
> > 
> > 
> > HI!, As I am a beginner in programming, I have learnt only HTML, CSS and a bit of JavaScript, so it was complex for me to create a website using JavaScript, and I had some timelines to submit this project so I needed to code in a platform suitable for me, so I choose GitHub and HTML, Thanks for raising this issue. I will try my best to make it using some other platform.
> 
> No, problem. It's totally fine using Github, but using Hostinger will make it run smoother. And just for the animations you can use Javascript which is not that hard. JS is one of the most easiest langs and even i thought at my early days that it's hard but it's not. Just a small lang change in your code will make your website much faster, smoother and easier to add more animations in future. BTW it's great, GOOD JOB!

Yes Sure, I will work more hard on JavaScript, and I will soon change the language for this website also

**Comment by aditineemkar** [comment]
> > > HI!, I'm a 13 year old dev too, as JavaScript being one of my first languages it's pretty impressive that you have made this without using JavaScript but just for better of this site, don't you think that this lags? I mean seriously is it just me or it actually lags?
> > > Also releasing it on Github is pretty confusing to me as you can use something like GoDaddy or Hostinger to get it up and running really quickly and easily, but yeah it's ur choice.
> > > I guess you should use something like Flask or JavaScript to make it smoother and better.
> > 
> > 
> > HI!, As I am a beginner in programming, I have learnt only HTML, CSS and a bit of JavaScript, so it was complex for me to create a website using JavaScript, and I had some timelines to submit this project so I needed to code in a platform suitable for me, so I choose GitHub and HTML, Thanks for raising this issue. I will try my best to make it using some other platform.
> 
> No, problem. It's totally fine using Github, but using Hostinger will make it run smoother. And just for the animations you can use Javascript which is not that hard. JS is one of the most easiest langs and even i thought at my early days that it's hard but it's not. Just a small lang change in your code will make your website much faster, smoother and easier to add more animations in future. BTW it's great, GOOD JOB!

Yeah sure!, I will work more harder on JS, and will soon change the language in this website also, and thnx for the appreciation!

**Comment by Light-Lens** [comment]
> > > > HI!, I'm a 13 year old dev too, as JavaScript being one of my first languages it's pretty impressive that you have made this without using JavaScript but just for better of this site, don't you think that this lags? I mean seriously is it just me or it actually lags?
> > > > Also releasing it on Github is pretty confusing to me as you can use something like GoDaddy or Hostinger to get it up and running really quickly and easily, but yeah it's ur choice.
> > > > I guess you should use something like Flask or JavaScript to make it smoother and better.
> > > 
> > > 
> > > HI!, As I am a beginner in programming, I have learnt only HTML, CSS and a bit of JavaScript, so it was complex for me to create a website using JavaScript, and I had some timelines to submit this project so I needed to code in a platform suitable for me, so I choose GitHub and HTML, Thanks for raising this issue. I will try my best to make it using some other platform.
> > 
> > 
> > No, problem. It's totally fine using Github, but using Hostinger will make it run smoother. And just for the animations you can use Javascript which is not that hard. JS is one of the most easiest langs and even i thought at my early days that it's hard but it's not. Just a small lang change in your code will make your website much faster, smoother and easier to add more animations in future. BTW it's great, GOOD JOB!
> 
> Yeah sure!, I will work more harder on JS, and will soon change the language in this website also, and thnx for the appreciation!

Talent must be appreciated!
Even programming in India is now growing, so it's my honor to contribute in the development of Software industry in India!
